version: "3.9"

services:
  app:
    build:
      context: ./docker/php
    container_name: Tsa-test-1
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    ports:
      - "9000:9000"

  web:
    image: nginx:latest
    container_name: nginx_web
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mariadb:latest
    container_name: mariadb_server
    restart: unless-stopped
    environment:
          MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
          MARIADB_DATABASE: ${DB_DATABASE}
          MARIADB_USER: ${DB_USERNAME}
          MARIADB_PASSWORD: ${DB_PASSWORD}
          MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
          # MARIADB_ROOT_PASSWORD_HASH:
          # MARIADB_RANDOM_ROOT_PASSWORD:
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  node:
    image: node:latest
    working_dir: /var/www/html
    container_name: node_builder
    volumes:
      - .:/var/www/html
    command: "tail -f /dev/null"

volumes:
  mariadb_data:


